### ISSUE TITLE
Items for JS map

### ISSUE THREAD

**Issue by wctestbank** [michaelpalumbo/achordingly#5]
![mockup_v2](https://user-images.githubusercontent.com/95963915/152461001-878164ed-bc64-4060-a72c-520e4006275a.png)

Local storage:
- [ ] Saved chord progression (Local storage object: SAVED PROGRESSION)

Session storage:
- [ ] Current Chords ( CHORD 1, CHORD 2...)

Storage Buttons:
- [ ] Save Session (CHORD 1, CHORD 2... -> SAVED PROGRESSION)
- [ ] Prior Chords (SAVED PROGRESSION... -> CHORD 1, CHORD 2...)
- [ ] Select New Starting Chord (CHORD 1 = BLANK...)

Chord Recommendation: 

- [ ] 3 Most common (CHORD 1 -> HOOKtheory API -> Top 3 probabilities)
- [ ] 3 Least common (CHORD 1 -> HOOKtheory API -> Bottom 3 probabilities)

Image:
- [ ] Staff Notation (CHORD  ->API 1 -> IMAGE)
- [ ] Fingering Diagram (CHORD  ->API 1 -> IMAGE)
- [ ] Piano Diagram (CHORD  ->API 1 -> IMAGE)

Sounds:
- [ ] Listen (CHORD  ->API 1 -> SOUND)

**Comment by Southern6236** [comment]
I believe this is the final layout we decided on! https://cdn.discordapp.com/attachments/938230678963757056/938985323722059786/mockup_v2.png

**Comment by michaelpalumbo** [comment]
@wctestbank Thanks a lot for doing this! I've copied each of these over as cards in the To Do Column of our trello board.

**Comment by michaelpalumbo** [comment]
![](https://cdn.discordapp.com/attachments/938230678963757056/938985323722059786/mockup_v2.png)
