### ISSUE TITLE
Login with Google on Hook Theory

### ISSUE THREAD

**Issue by shookspear** [michaelpalumbo/achordingly#6]
We need to allow users to login to Hook Theory using Google and still be able to connect with the API.

When you sign up to Hook Theory via Google you are prompted to select a username but no password.

**Comment by michaelpalumbo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [JS/CSS: Login with Google on HookTheory](https://trello.com/c/yL5dO6qe/18-js-css-login-with-google-on-hooktheory)

**Comment by michaelpalumbo** [comment]
As I’m thinking through it, it seems like that wouldn’t be possible because the integration is between google and Hooktheory, and we wouldn’t be able to insert ourselves in between that exchange. I've posted this question to the class and will also keep looking into it on forums and will post experiments.

**Comment by michaelpalumbo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [JS/CSS: Login with Google on HookTheory](https://trello.com/c/yL5dO6qe/18-js-css-login-with-google-on-hooktheory)

**Comment by michaelpalumbo** [comment]
@shookspear can you try signing into our app using your gmail address and password, just to see if that works?

**Comment by michaelpalumbo** [comment]
Thanks @shookspear . In that case, think we ought to just add a stipulation in the login modal that says users can *only* signup using their email, not using the google integration. Chris responded to this question in slack with:

> doing this type of auth with a third party app, purely client-side is possible, but really tricky.  I think you might want to wait for this type of integration for project 2! IMHO!

I know that it is not as nice a user experience, but I think there are more pressing items in the MVP to tackle, and Chris gave us a pass on this.

**Comment by shookspear** [comment]
I changed my password and was able to log in. It's saying "Accessing chord database, please wait..." but I presume it's a work in progress

**Comment by michaelpalumbo** [comment]
Hmm @shookspear is it hung on that message, or does it go away after ~5 seconds (as it is meant to)?

**Comment by michaelpalumbo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [stipulation in the login that users need to change their hooktheory password manually if they joined via google auth.](https://trello.com/c/v9eZd4fB/45-stipulation-in-the-login-that-users-need-to-change-their-hooktheory-password-manually-if-they-joined-via-google-auth)

**Comment by michaelpalumbo** [comment]
@shookspear i'm opening a new issue for the error you described. i see it too and i know whats wrong. i'll add a fix but we'll need to do another PR
